config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
  root to: "static_pages#index"
  resources :categories, only: :show
  resources :products, only: :show
  root to: "static_pages#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  resources :carts, only: %i(index)
  post "carts", to: "carts#update"
  delete "carts", to: "carts#destroy"

  resources :charges, only: %i(create)
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize user
    user ||= User.new
    can :read, :all
    return unless user.has_role? :admin

    can :access, :rails_admin
    can :read, :dashboard
    can :manage, [User, Product, Category]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :user_id, presence: true
  validates :product_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
  resourcify
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :category
  resourcify

  selected_by :user
  validates :name, presence: true
  validates :price, presence: true,
            format: { with: /\A\d+(?:\.\d{0,2})?\z/ },
            numericality: { greater_than: 0, less_than: 1000000 }

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
    polymorphic: true,
    optional: true

  validates :resource_type,
    inclusion: {in: Rolify.resource_types},
    allow_nil: true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  devise :database_authenticatable, :registerable, :recoverable,
         :rememberable, :validatable, :confirmable
  
  def send_devise_notification notification, *args
    devise_mailer.send(notification, self, *args).deliver_later
  end
  
  selecting :product
  
  has_many :credit_cards, dependent: :destroy
  has_many :bills, dependent: :destroy
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: true
  
  def total_cart_costs
    self.carts.
      inject(0) {|result, cart| result + cart.product.price * cart.quantity}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_categories
  
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_path, alert: exception.message
  end
  
  def get_categories
    @categories = Category.all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :load_product, only: %i(update destroy)

  def index
    redirect_to root_path unless current_user
    @total = current_user.total_cart_costs
  end

  def update
    if params[:btn_type] == "add"
      product_qty = params[:product_qty].to_i

      current_user.add_multiple_to_cart @product, product_qty
    elsif params[:btn_type] == "remove"
      current_user.remove_from_cart @product
    end

    respond_to do |f|
      f.html {redirect_to :carts}
      f.js
    end
  end

  def destroy
    item = Cart.find_by user_id: current_user.id, product_id: @product.id

    if item.destroy
      respond_to do |f|
        f.html {redirect_to :carts}
        f.js
      end
    else
      flash[:notice] = t ".fail_to_delete_item"
    end
  end

  private

  def load_product
    @product = Product.find_by id: params[:product_id]

    redirect_to main_app.root_path unless @product
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category
  
  def show
    @products = @category.products
  end
  
  def load_category
    @category = Category.find_by id: params[:id]
  
    return if @category
    flash[:warning] = t ".category_not_found"
    redirect_to root_url
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!

  rescue_from Stripe::CardError do |e|
    redirect_to main_app.root_path, alert: e.message
  end

  def create
    StripeChargesService.new(charges_params, current_user).call
    current_user.carts.each do |c|
      Bill.create(
        product: c.product,
        user: current_user,
        quantity: c.quantity)
    end
    Cart.where(user_id: current_user.id).delete_all
    flash[:info] = t ".succeed_in_payment"
    redirect_to main_app.carts_path
  end

  private

  def charges_params
    params.permit(:stripeEmail, :stripeToken)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find_by id: params[:id]
    @products = Product.where(category: @product.category)
                  .where.not(id: @product.id)
    return if @product
    flash[:warning] = t ".product_not_found"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @q = Product.ransack name_cont: params[:q]
    @products = @q.result.page(params[:page]).per(7)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit :sign_up, keys: [:name]
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit :account_update, keys: [:name]
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  respond_to :json

  def new
    redirect_to root_url
  end

  def create
    self.resource = warden.authenticate!(auth_options)
    sign_in_and_redirect(resource_name, resource)
  end

  def sign_in_and_redirect resource_or_scope, resource
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource
    respond_to do |format|
      format.json{render json: {success: true}}
    end
  end

  def failure
    warden.custom_failure!
    respond_to do |format|
      format.json{render json: {success: false}}
    end
  end

  protected

  def auth_options
    {scope: resource_name, recall: "#{controller_path}#failure"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/carts/_bill.html.erb
<td><img width="60" src=<%= bill.product.image.url %> alt=""/></td>
<td><%= bill.product.name %></td>
<td>
  <%= bill.quantity %>
</td>
<td>$<%= bill.product.price %></td>
<td>$<%= bill.product.price * bill.quantity %></td>
<td><%= bill.created_at %></td>

app/views/carts/destroy.js.erb
$("#product_<%= @product.id %>").remove()
$("#total_cost").html('<%= current_user.total_cart_costs %>')

app/views/carts/index.html.erb
<div class="span9">
  <ul class="breadcrumb">
    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
    <li class="active"> SHOPPING CART</li>
  </ul>
  <h5> Carts </h5>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Product</th>
      <th>Name</th>
      <th>Quantity/Update</th>
      <th>Price</th>
      <th>Total</th>
    </tr>
    </thead>
    <tbody>
    <% if current_user %>
      <% current_user.selecting_products.each do |product| %>
        <tr id=<%= "product_#{product.id}" %>>
          <%= render partial: "products/in_cart_product", locals: {product: product} %>
        </tr>
      <% end %>
    <% end %>
    <tr>
      <td colspan="4" style="text-align:right"><strong>TOTAL=</strong></td>
      <td class="label label-important" style="display:block">
        <strong>
          <span id="total_cost">$<%= @total %> </span>
        </strong>
      </td>
    </tr>
    <tr>
      <td colspan="5" style="text-align:right">
        <%= form_tag charges_path do %>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
          <% if @total > 0 %>
            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                    data-email="<%= current_user.email %>"
                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                    data-locale="auto">
            </script>
          <% end %>

        <% end %>
      </td>
    </tr>
    </tbody>
  </table>
  <h5> History </h5>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>Product</th>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total</th>
      <th>Date</th>
    </tr>
    </thead>
    <tbody>
    <% if current_user %>
      <% current_user.bills.each do |bill| %>
        <%= render partial: "bill", locals: {bill: bill} %>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>

</div>

app/views/carts/update.js.erb
$("#product_<%= @product.id %>")
    .html('<%= j render partial: "products/in_cart_product", locals: {product: @product} %>')

$("#total_cost").html('<%= current_user.total_cart_costs %>')

app/views/categories/show.html.erb
<%#= @category.name %>
<%# @products.each do |product| %>
<%#= render "static_pages/latest_product", product: product %>
<%# end %>
<div class="span9">
  <ul class="breadcrumb">
    <li>
      <%= link_to "Home", root_path %> <span class="divider">/</span>
    </li>
    <li class="active"><%= @category.name %></li>
  </ul>
  <h3> <%= @category.name %>
    <small class="pull-right"> <%= @category.products.size %> products are available</small>
  </h3>
  <hr class="soft"/>
  <p>
    Nowadays the lingerie industry is one of the most successful business spheres.We always stay in touch with the
    latest fashion tendencies - that is why our goods are so popular and we have a great number of faithful customers
    all over the country.
  </p>
  <hr class="soft"/>
  <ul class="thumbnails">
    <% @products[0..5].each do |p| %>
      <li class="span3">
        <%= render "static_pages/latest_product", product: p %>
      </li>
    <% end %>
  </ul>

  <br class="clr"/>
</div>

app/views/products/_in_cart_product.html.erb
<td><img width="60" src=<%= product.image.url %> alt=""/></td>
<td><%= product.name %></td>
<td>
  <div class="input-append">
    <% quantity = current_user.show_cart.where(product_id: product.id).pluck(:quantity)[0] %>
    <input class="span1" style="max-width:34px"
           value=<%= quantity %>
               id="appendedInputButtons" size="16" type="text">
    <%= form_tag carts_path, remote: true, style: "display:inline" do %>
      <%= hidden_field_tag "btn_type", "remove" %>
      <%= hidden_field_tag "product_id", product.id %>
      <button class="btn" type="submit"><%= fa_icon "minus" %></i></button>
    <% end %>

    <%= form_tag carts_path, remote: true, style: "display:inline" do %>
      <%= hidden_field_tag "btn_type", "add" %>
      <%= hidden_field_tag "product_qty", "1" %>
      <%= hidden_field_tag "product_id", product.id %>
      <button class="btn" type="submit">
        <%= fa_icon "plus" %></i>
      </button>
    <% end %>
    <%= form_tag carts_path, remote:true, method: :delete, style: "display:inline" do %>
      <%= hidden_field_tag "btn_type", "remove" %>
      <%= hidden_field_tag "product_id", product.id %>
      <button class="btn btn-danger" type="submit"><%= fa_icon "trash" %></button>
    <% end %>

  </div>
</td>
<td>$<%= product.price %></td>
<td>$<%= product.price * quantity %></td>

app/views/products/_product_details.html.erb
<div class="tab-pane fade active in" id="home">
  <h4>Product Information</h4>
  <table class="table table-bordered">
    <tbody>
    <tr class="techSpecRow">
      <th colspan="2">Product Details</th>
    </tr>
    <tr class="techSpecRow">
      <td class="techSpecTD1">Brand:</td>
      <td class="techSpecTD2">Fujifilm</td>
    </tr>
    <tr class="techSpecRow">
      <td class="techSpecTD1">Model:</td>
      <td class="techSpecTD2">FinePix S2950HD</td>
    </tr>
    <tr class="techSpecRow">
      <td class="techSpecTD1">Released on:</td>
      <td class="techSpecTD2"> 2011-01-28</td>
    </tr>
    <tr class="techSpecRow">
      <td class="techSpecTD1">Dimensions:</td>
      <td class="techSpecTD2"> 5.50" h x 5.50" w x 2.00" l, .75 pounds</td>
    </tr>
    <tr class="techSpecRow">
      <td class="techSpecTD1">Display size:</td>
      <td class="techSpecTD2">3</td>
    </tr>
    </tbody>
  </table>

  <h5>Features</h5>
  <p>
    14 Megapixels. 18.0 x Optical Zoom. 3.0-inch LCD Screen. Full HD photos and 1280 x 720p HD movie capture.
    ISO sensitivity ISO6400 at reduced resolution. Tracking Auto Focus. Motion Panorama Mode. Face Detection
    technology with Blink detection and Smile and shoot mode. 4 x AA batteries not included. WxDxH 110.2
    ×81.4x73.4mm. Weight 0.341kg (excluding battery and memory card). Weight 0.437kg (including battery and
    memory card).<br/>
    OND363338
  </p>

  <h4>Editorial Reviews</h4>
  <h5>Manufacturer's Description </h5>
  <p>
    With a generous 18x Fujinon optical zoom lens, the S2950 really packs a punch, especially when matched with
    its 14 megapixel sensor, large 3.0" LCD screen and 720p HD (30fps) movie capture.
  </p>

  <h5>Electric powered Fujinon 18x zoom lens</h5>
  <p>
    The S2950 sports an impressive 28mm – 504mm* high precision Fujinon optical zoom lens. Simple to operate
    with an electric powered zoom lever, the huge zoom range means that you can capture all the detail, even
    when you're at a considerable distance away. You can even operate the zoom during video shooting. Unlike a
    bulky D-SLR, bridge cameras allow you great versatility of zoom, without the hassle of carrying a bag of
    lenses.
  </p>
  <h5>Impressive panoramas</h5>
  <p>
    With its easy to use Panoramic shooting mode you can get creative on the S2950, however basic your skills,
    and rest assured that you will not risk shooting uneven landscapes or shaky horizons. The camera enables you
    to take three successive shots with a helpful tool which automatically releases the shutter once the images
    are fully aligned to seamlessly stitch the shots together in-camera. It's so easy and the results are
    impressive.
  </p>

  <h5>Sharp, clear shots</h5>
  <p>
    Even at the longest zoom settings or in the most challenging of lighting conditions, the S2950 is able to
    produce crisp, clean results. With its mechanically stabilised 1/2 3", 14 megapixel CCD sensor, and high ISO
    sensitivity settings, Fujifilm's Dual Image Stabilisation technology combines to reduce the blurring effects
    of both hand-shake and subject movement to provide superb pictures.
  </p>
</div>

app/views/products/_related_products.html.erb
<div class="tab-pane fade" id="profile">
  <div class="tab-content">
    <div class="tab-pane active" id="blockView">
      <ul class="thumbnails">
        <% @products.each do |p| %>
          <li class="span3">
            <%= render "static_pages/latest_product", product: p %>
          </li>
        <% end %>
      </ul>

      <hr class="soft"/>
    </div>
  </div>
  <br class="clr">
</div>

app/views/products/show.html.erb
<div class="span9">
  <ul class="breadcrumb">
    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
    <li><a href="products.html">Products</a> <span class="divider">/</span></li>
    <li class="active"><%= @product.name %></li>
  </ul>
  <div class="row">
    <div id="gallery" class="span3">
      <%= image_tag @product.image.url %>
    </div>
    <div class="span6">
      <h3><%= @product.name %></h3>
      <small>Some description</small>
      <hr class="soft"/>
      <%= form_tag carts_path, class: "form-horizontal qtyFrm" do %>
        <%= hidden_field_tag "btn_type", "add" %>
        <%= hidden_field_tag "product_id", @product.id %>
        <div class="control-group">
          <label class="control-label"><span>
            $<%= @product.price %>
          </span></label>
          <div class="controls">
              <input type="number" min="1" value="1" class="span1" name="product_qty"/>
            <button type="submit" class="btn btn-large btn-primary pull-right"> Add to cart
              <i class=" icon-shopping-cart"></i></button>
          </div>
        </div>
      <% end %>
      <form class="form-horizontal qtyFrm">

      </form>

      <hr class="soft clr"/>
      <p>
        14 Megapixels. 18.0 x Optical Zoom. 3.0-inch LCD Screen. Full HD photos and 1280 x 720p HD movie capture. ISO
        sensitivity ISO6400 at reduced resolution.
        Tracking Auto Focus. Motion Panorama Mode. Face Detection technology with Blink detection and Smile and shoot
        mode. 4 x AA batteries not included. WxDxH 110.2 ×81.4x73.4mm.
        Weight 0.341kg (excluding battery and memory card). Weight 0.437kg (including battery and memory card).

      </p>
      <br class="clr"/>
      <a href="#" name="detail"></a>
      <hr class="soft"/>
    </div>

    <div class="span9">
      <ul id="productDetail" class="nav nav-tabs">
        <li class="active"><a href="#home" data-toggle="tab">Product Details</a></li>
        <li><a href="#profile" data-toggle="tab">Related Products</a></li>
      </ul>
      <div id="myTabContent" class="tab-content">
        <%= render "product_details" %>
        <%= render "related_products" %>
      </div>
    </div>

  </div>
</div>

app/views/static_pages/_carousel.html.erb
<div id="carouselBlk">
  <div id="myCarousel" class="carousel slide">
    <div class="carousel-inner">
      <div class="item active">
        <div class="container">
          <a href="register.html"><img style="width:100%" src="/images/carousel/2.png" alt=""/></a>
        </div>
      </div>
      <div class="item">
        <div class="container">
          <a href="register.html"><img src="/images/carousel/3.png" alt=""/></a>
        </div>
      </div>
      <div class="item">
        <div class="container">
          <a href="register.html"><img src="/images/carousel/4.png" alt=""/></a>
        </div>
      </div>
      <div class="item">
        <div class="container">
          <a href="register.html"><img src="/images/carousel/5.png" alt=""/></a>
        </div>
      </div>
      <div class="item">
        <div class="container">
          <a href="register.html"><img src="/images/carousel/6.png" alt=""/></a>
        </div>
      </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
  </div>
</div>

app/views/static_pages/_feature_product.html.erb
<div class="thumbnail">
  <i class="tag"></i>
  <a href="product_details.html">
    <%= image_tag product.image.url %>
  </a>
  <div class="caption" style="white-space: nowrap;">
    <h5><%= product.name %></h5>
    <h4>
      <%= link_to "VIEW", product, class: "btn" %>
      <span class="pull-right">$<%= product.price %></span>
    </h4>
  </div>
</div>

app/views/static_pages/_feature_products.html.erb
<div class="well well-small">
  <h4>Featured Products
  </h4>
  <div class="row-fluid">
    <div id="featured" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <ul class="thumbnails">
            <% Product.all[0..3].each do |p| %>
              <li class="span3">
                <%= render "feature_product", product: p %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="item">
          <ul class="thumbnails">
            <% Product.all[4..7].each do |p| %>
              <li class="span3">
                <%= render "feature_product", product: p %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <a class="left carousel-control" href="#featured" data-slide="prev">‹</a>
      <a class="right carousel-control" href="#featured" data-slide="next">›</a>
    </div>
  </div>
</div>

app/views/static_pages/_latest_product.html.erb
<div class="thumbnail">
  <a href="product_details.html">
    <%= image_tag product.image.url %>
  </a>
  <div class="caption">
    <h5><%= product.name %></h5>
    <p>
      Some description
    </p>
    <h4 style="text-align:center">
      <%= link_to fa_icon("search-plus"), product, class: "btn" %>
<!--      <div id=<%#= "form_add_product_#{product.id}" %>>-->
        <%#= form_tag carts_path, remote: true do %>
          <%#= hidden_field_tag "btn_type", "add" %>
          <%#= hidden_field_tag "product_id", product.id %>
          <%#= button_tag "Add", class: "btn"%>
        <%# end %>
<!--      </div>-->
<!--      <div hidden id=<%#= "form_remove_product_#{product.id}" %>>-->
        <%#= form_tag carts_path, remote: true do %>
          <%#= hidden_field_tag "btn_type", "remove" %>
          <%#= hidden_field_tag "product_id", product.id %>
          <%#= button_tag "Remove", class: "btn"%>
        <%# end %>
<!--      </div>-->
<!--      <a class="btn" href="#">Add to <%#= fa_icon "shopping-cart" %></i></a>-->
      <span class="btn btn-primary" href="#">
        $<%= product.price %>
      </span>
    </h4>
  </div>
</div>

app/views/static_pages/_latest_products.html.erb
<h4>Latest Products </h4>
<%= paginate @products %>

<ul class="thumbnails">

  <% @products.each do |p| %>
    <li class="span3">
      <%= render "latest_product", product: p %>
    </li>
  <% end %>

</ul>

app/views/static_pages/index.html.erb
<% content_for :carousel do %>
  <%= render "carousel" %>
<% end %>

<div class="span9">
  <%= render "feature_products" %>
  <%= render "latest_products" %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t(".sign_in"), new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t(".sign_up"), new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to t(".forgot_your_password"), new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>